version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - API_KEY=your_secret_api_key
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
