version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
